language: c
compiler:
  - gcc

env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "TdSvCprPeAUbYYEoZDPocAjOImCbi05o2GLLEdiGQYmLtR7I3qx2MeQ7LjeveVqD0AzS+eAxL+OSjcBS5DA4gXGOVJqQAfclJLJ57MafdoTVzOxGsfqHcyKDo3L3N8nD3AbICeFS+foeCX22bqf9iZiEp0MmxYQ7DvFlc+jCqGk="
   
addons:
  coverity_scan:
    project:
      name: "daksheshvyas/MyHelloWorld"
      description: "Your project description here"
    notification_email: daksheshvyas@hotmail.com
    build_command_prepend: "./configure"
    build_command: "make -j2"
    branch_pattern: master


    
script:
  - make -j2   



#    build_script_url: https://raw.githubusercontent.com/daksheshvyas/CoverityTravisScan/master/scan_script.sh
