language: c
compiler:
  - gcc
  
env:
  global:
    # Your normal Travis CI build command
    # Normally this would be in the script: tag of .travis.yml, instead place it here
    - STANDARD_BUILD_COMMAND="gcc HelloWorld.c"

    # -- BEGIN Coverity Scan ENV

    # Pre-configuration steps that should not be analyzed
    # i.e. "./configure"
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND=""

    # The build command with all of the arguments that you would apply to a manual `cov-build`
    # Usually this is the same as STANDARD_BUILD_COMMAND, exluding the automated test arguments
    #
    # Examples:
    # make -j4
    # mvn -f pom.xml
    # ant -buildfile test.xml
    - COVERITY_SCAN_BUILD_COMMAND="gcc HelloWorld.c"

    - PROJECT_NAME="daksheshvyas/MyHelloWorld"

    # Email address for notifications related to this build
    - OWNER_EMAIL="scan-admin@coverity.com"

    # Regular expression selects on which branches to run analysis
    # Be aware of quotas. Do not run on every branch/commit
    - COVERITY_SCAN_BRANCH_PATTERN="coverity_scan"

    # COVERITY_SCAN_TOKEN via "travis encrypt" using the repo's public key
    - secure: "hiMqthJk1RtWGYv4QaCTyWzlqIZIcu4VMPrGSX9zsjn9+twwOu5FIo15OoBXcVFdON+ubKnJXY6oTwALHyJN+Ai0wyIn1CP91zQwhgwQLYrGsEi0Mt6zNCy0NXwNkGarzH/XMwfD41Cp7vxX4ZZOA968LHOQhUMuZ9D2l7hA4+Y="

    - COVERITY_SCAN_BUILD_URL="http://scan.coverity.com/scripts/travisci_build_coverity_scan.sh"
    - COVERITY_SCAN_BUILD="curl -s $COVERITY_SCAN_BUILD_URL | bash"

    # -- END Coverity Scan ENV

  # Note: Your build matrix configuration may vary. Consult Travis CI Docs for more information
  # http://docs.travis-ci.com/user/build-configuration/#The-Build-Matrix
  matrix:
    - COVERITY_SCAN=0
    - COVERITY_SCAN=1

script:
  # Move your original Travis CI build command to STANDARD_BUILD_COMMAND, above
  - if [ "${COVERITY_SCAN}" = '1' ]; then eval "$COVERITY_SCAN_BUILD"; else eval "$STANDARD_BUILD_COMMAND"; fi
